import solutions.Day5

fun main() {
    try {
        Day5().solution2()
    } catch (exception: Exception) {
        print("\n ${exception.stackTrace.contentToString()} \n")
    }
}