import solutions.*

fun main() {
    try {
        Day12().solution2()
    } catch (exception: Exception) {
        print("\n ${exception.stackTrace.contentToString()} \n")
    }
}